### ISSUE TITLE
Configure `DisableNullChecks` at query and/or mapper level

### ISSUE THREAD

**Issue by k94ll13nn3** [alirezanet/Gridify#238]
### Details

Hi, would it be possible to allow the configuration of `DisableNullChecks` and/or `EntityFrameworkCompatibilityLayer` in the mapper configuration or when executing the query? 
I want to use Gridify in a shared package in our company, but I want to be sure that the configuration stays the same depdending on what configuration the consumers have since what I will be doing requires a specific value for these properties.

**Comment by alirezanet** [comment]
Hi @k94ll13nn3,

Unfortunately, this isn't possible at the moment. This issue is related to #179. Currently, these settings can only be used globally. However, I'm planning to release a new version that addresses this problem. The main obstacle is the breaking changes required to implement this feature, as it necessitates changes to the static global configuration class. (we should remove it)

I anticipate that this will be available in the next major version.

**Comment by alirezanet** [comment]
Although ... 🤔
I initially thought it wasn't possible, but after reconsidering, it might be feasible without changing the global configuration implementation. I'll take a closer look and see if we can add this feature sooner.
